### ISSUE TITLE
Add 'Next activity' link

### ISSUE THREAD

**Issue by daveyboond** [blackboard-open-source/moodle-theme_snap#128]
We are using Snap for wholly-online courses, and there's one way in which our students find Snap difficult to navigate. For such courses, students are completing activities in order. However, having completed a resource or activity, the only way they can proceed is to go back to the home page, then scroll back down to the next activity along.

It would be much easier if each activity presented, at its foot, a link leading to the next visible activity along - in much the same way that each section provides a link to the next section at its foot.

Does this seem like a good idea?

**Comment by gthomas2** [comment]
I like this idea but unfortunately adding new features is not within my remit.

**Comment by daveyboond** [comment]
I've just installed the latest MOODLE_34_STABLE and I find that the above functionality has suddenly appeared! Obviously this was within someone else's remit :)

Thank you, whoever added this feature!
