### ISSUE TITLE
Course dashboard grade display is often wrong

### ISSUE THREAD

**Issue by rrusso** [blackboard-open-source/moodle-theme_snap#134]
Course dashboard grade display for students is wrong when grade is within the 0 decimal place rounding boundary and the course uses > 0 decimal places for grading.

In classes/course_total_grade.php on line 170 you neglect to call the decimals preference for the course total and never even use the 2 decimal default, therefore it uses PHP default of 0 decimal places which will incorrectly inflate the student grade.

This is a TRIVIAL fix that should not have been overlooked.

**Comment by dvdcastro** [comment]
Fixed in ea05dc83af8fadaae252b8f3f86c3ecdb3887231 Thanks for reporting
