### ISSUE TITLE
Message Moodle 3.6

### ISSUE THREAD

**Issue by przemekszlagor** [blackboard-open-source/moodle-theme_snap#136]
How to fix an issue when Snap doesn't show message system in Moodle 3.6. Can I do it myself or should I wait for update?

**Comment by MarcioQuimbundo** [comment]
did you solve @przemekszlagor  ??

**Comment by przemekszlagor** [comment]
No :(

**Comment by MarcioQuimbundo** [comment]
:(

**Comment by MarcioQuimbundo** [comment]
I fixed the bug

add this code inside layout > default.php in line 146, after closing div with id="page-content"

<?php echo $OUTPUT->standard_after_main_region_html() ?>

Good Lucky

:)

**Comment by labulatif** [comment]
Hi Marcio,
In my case the code didn't work.
Could you check what I'm doing wrong?
=======================================

</div>
</div>
<id="page-content" standard_after_main_region_html() ?>

<?php // @codingStandardsIgnoreEnd

================================================

**Comment by dvdcastro** [comment]
Hello,

We fixed this for later versions of Snap, we are currently not supporting Snap 3.6.
