### ISSUE TITLE
Error in login only when using Snap theme

### ISSUE THREAD

**Issue by Alandette** [blackboard-open-source/moodle-theme_snap#137]
An error message is displayed when trying to enter Moodle with the theme Snap activated.

Users use their access data but the system indicates that the data is wrong, however this error disappears when changing the graphic theme (Boost for example).

One way to avoid this error is to add the following line in the Moodle config.php file

$ CFG-> disablelogintoken = true;
However, I understand that doing so is not a good practice.

I have verified and the following line of code is present in the entry forms:
<input type = "hidden" name = "logintoken" value = "{{logintoken}}">

We appreciate if someone knows where else we can review to solve the error.

The data of the installation are the following:
Moodle 3.4.7 (Build: 20190114)
PHP Version 7.0.33-1 + ubuntu14.04.1
Snap 3.4.3

Thank you

**Comment by dvdcastro** [comment]
Hello,

We no longer support Snap 3.4, but we did fix this issue for later versions. We are currently supporting Snap 3.7 and will support Snap 3.8 after summer.
