### ISSUE TITLE
fix for 3.7

### ISSUE THREAD

**Issue by rrusso** [blackboard-open-source/moodle-theme_snap#143]
https://github.com/blackboard-open-source/moodle-theme_snap/blob/c01e029a1c18eb48cb68ab4ed543a138880f0b65/classes/output/core_course/management/renderer.php#L39

Should read

class renderer extends \core_course_management_renderer {

now that all the renderers have been moved into core. Still ironing out some other 3.7 issues.

**Comment by rrusso** [comment]
Looks like the only remaining 3.7 issues are in unit tests only.

**Comment by dvdcastro** [comment]
Fixed on cba343f503ec01ea6470780e02caec3c2b647778
