### ISSUE TITLE
Admin menu tree is partially obscured on mobile portrait screen widths

### ISSUE THREAD

**Issue by pcomel** [blackboard-open-source/moodle-theme_snap#147]
Bootstrap 4 p-3 is overriding CSS media queries for the **admin menu tree**.

_Note: this issue is happening on an Open LMS' Moodle 3.6.x instance._

With p-3 class (**current**):
![img](https://i.imgur.com/O9flfdM.png)

Without the p-3 class (**ideal**):
![img](https://i.imgur.com/RdCVrxs.png)

**Comment by Dizolivemint** [comment]
This is also the case with other elements on other pages.
For example, the purge caches page, the top of the text is obscured.

**Comment by Dizolivemint** [comment]
Looks like Moodle core changed to Bootstrap 4 and there needs to be some restructuring of CSS architecture.

**Comment by dvdcastro** [comment]
Hello,

I think we fixed this for Snap 3.7 on these commits:

28b6e59b8b5bf5cfb3e55f44dc4d691b008fdd94
e747fbef1e5d8d9fb4631ed57a448dbf00d27a5c

We are not supporting Snap 3.6 at the moment, only 3.7 until summer 2020 and 3.8 afterwards.
