### ISSUE TITLE
Manual completion does not update on Snap 3.5

### ISSUE THREAD

**Issue by jjliaw** [blackboard-open-source/moodle-theme_snap#149]
Just wanted to report a small bug that Snap 3.5 does not update manual completion of activities for students.

In the older Snap versions, students could click on the grey checkbox and it would turn green for them on their course page.

Now, students, need to refresh the page after clicking, and then it turns green--but sometimes they get confused and click twice, and the box changes back to grey which is very confusing and counter-intuitive.

Thanks for looking into this and sharing your amazing work with the Moodle community!  Snap is the most student-friendly UX I have ever seen and makes building engaging courses truly  enjoyable for instructors and learners alike!

**Comment by dvdcastro** [comment]
Hello,

We are no longer supporting the 3.5 version. Could you replicate on the 3.7 version so we review if this is still happening?
