### ISSUE TITLE
Footer not saved

### ISSUE THREAD

**Issue by musyne** [blackboard-open-source/moodle-theme_snap#151]
Hi,
When I change the site footer in /admin/settings.php?section=themesettingsnap my new content is saved (in the settings) but the footer doesn't change on the website. I've purged all cache but it's still the old footer.
I'm using Moodle 3.4.4+ (Build: 20180831) and Snap 3.4.3 (2018080800)
Website: https://moodle.aflahaye.nl/
Any suggestion?

**Comment by dvdcastro** [comment]
Hello, we no longer support Snap 3.4. Can you verify in Snap 3.7 which we are currently supporting?
