### ISSUE TITLE
manual completion not working properly in Snap 3.5

### ISSUE THREAD

**Issue by jjliaw** [blackboard-open-source/moodle-theme_snap#154]
Wanted to report that if a teacher activates manual completion for a Page resource, Snap 3.5 will not show the page resource when a student clicks "Read More" and will simply get a "Loading..." message with nothing showing up!

Also, manual activity completion used to update as soon as a student clicked on the grey check mark, but now a student has to refresh the page in order for it to show up.

This breaks courses where activity completion is built in by instructors for creating mastery paths and differentiation in learning paths for students (e.g. complete set of notes and podcasts in order to unlock a quiz, answer key, etc.).

Any suggestions on how to fix this or a way to squash this bug would be greatly appreciated!  

Thank you for sharing your fantastic work with the Moodle community--Snap is still the most user friendly experience for teaching and learning by far!!!

**Comment by dvdcastro** [comment]
Hello, we are not supporting this version of Snap anymore.
