### ISSUE TITLE
Snap 3.6.3 Section text not saving

### ISSUE THREAD

**Issue by gocchipinti** [blackboard-open-source/moodle-theme_snap#155]
HI all,

we are experiencing a technical issue with course sections; whenever I create a new section on a course two things happen:
1- a 150 appears there as default
2 - any text added to the 'Contents' section disappears after clicking on 'create section'

Once the section is created, the problem seems to disappear.

![snap issue](https://user-images.githubusercontent.com/55984766/65878876-f3fbd080-e386-11e9-8af4-4cecc8643960.png

This is proving annoying for staff that are reporting the problem, as they are losing work.

Thanks

**Comment by andrewrowatt-masseyuni** [comment]
I can confirm this issue on both our self-hosted Moodle and our OpenLMS sites.  All are running 3.6.3 - 20190515xx.

**Comment by andrewrowatt-masseyuni** [comment]
@gocchipinti we developed a "fix" using CSS while we want for the issue to be resolved.  Happy to share this.

**Comment by gocchipinti** [comment]
Hi Andrew, that would be extremely helpful. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andrewrowatt-masseyuni** [comment]
@gocchipinti here it is:
/* Snap 3.6 (Moodle 3.7) bug workaround MU040 */
#snap-add-new-section form div[class=form-group]:nth-of-type(2) {
    display: none;
}

#snap-add-new-section form div[class=form-group]:nth-of-type(1)::after {
    content: "Due to a known issue with the Snap theme, section content cannot be added when creating a new section.  First create the section (using this screen) and then edit the section to add content.";
color: #856404;
    border: 1px solid #ffeeba;
border-radius: .25rem;
    background-color: #fff3cd;
    display: block;
    padding: 1em;
    margin-top: 1em;
}

![image](https://user-images.githubusercontent.com/5333879/69084297-d276b580-0aa8-11ea-9e6f-fe34f56c4976.png)

**Comment by dvdcastro** [comment]
Hello,

Thanks for reporting.

We fixed this issue for Snap 3.7 in 5ae7c14.
