### ISSUE TITLE
End users unable to alter 'File' appearance settings

### ISSUE THREAD

**Issue by sampash** [blackboard-open-source/moodle-theme_snap#156]
![appearance settings](https://user-images.githubusercontent.com/57447551/68305959-81c28e00-00a0-11ea-90e3-36f61ab19011.png)
The appearance settings, as shown in the image, do not appear in the Snap theme.
I have tested this out by changing the appearance to a different theme and they show fine, so I know it is not a role issue.

There appears to be something in the theme that is hiding it (see: https://moodle.org/mod/forum/discuss.php?d=392839#p1584941)

Thanks,
Sam

**Comment by sampash** [comment]
If you need any more details, let me know.

**Comment by dvdcastro** [comment]
Hello @sampash thanks for reporting.

The lack of appearance settings for Snap is a "By design" decision, since those attributes will not be rendered in the course page when using Snap.

We will, however, evaluate if we can show them in a different way so as to keep our design principles in place.
