### ISSUE TITLE
Unbolding in Atto editor not working

### ISSUE THREAD

**Issue by andrewrowatt-masseyuni** [blackboard-open-source/moodle-theme_snap#157]
Hi Team,

For some reason when using the Atto editor users can bold text but cannot unbold.  Either using the toolbar icon or Ctrl-B.  If I switch the theme to Classic (for example) the problem is not there.

This is occurring on my Open LMS sandbox (3.7.3) and our installation.   I am not capable of debugging this any further so any advice appreciated.

Thanks,
   Andrew

**Comment by andrewrowatt-masseyuni** [comment]
I've just checked our Moodle 3.5 site.  The same problem exists.  So not new, we have just been alerted to it.  

I also checked our production Open LMS site - the problem does not exist there.

If someone else could confirm this issue that would be most helpful.

**Comment by upats** [comment]
Hi, I have a site running Moodle 3.5.9+ and Snap theme version 3.5.2 but I am *not* seeing an issue unbolding text. I just tested on a course page in a label.

**Comment by andrewrowatt-masseyuni** [comment]
> Hi, I have a site running Moodle 3.5.9+ and Snap theme version 3.5.2 but I am _not_ seeing an issue unbolding text. I just tested on a course page in a label.

Thanks.  Our 3.5 site is Moodle 3.5.7+ (Build: 20190712) and Snap 3.5.2 (2018080801).  That site has the issue.

**Comment by dvdcastro** [comment]
Hello,

It seems like we fixed that for newer versions of Snap.

I could not replicate on 3.7.3.

We don't patch older versions of the theme unless it is a very hard thing to miss, but we are more than 2 versions ahead right now, feel free to share a PR and we'll see if we can have that fixed for your version.
