### ISSUE TITLE
Delete section footer alert doesn't show title

### ISSUE THREAD

**Issue by PickledKitty** [blackboard-open-source/moodle-theme_snap#164]
The order in which the footerAlert.setTitle appears under 'var sectionDelete' is incorrect. As it stands, no title is injected into the alert footer, but changing it to this works:

footerAlert.addAjaxLoading('');
footerAlert.show();
footerAlert.setTitle(delProgress);

**Comment by dvdcastro** [comment]
Thanks, we'll be fixing this.
